//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ExprParser.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ExprParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface IExprParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] ExprParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] ExprParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc([NotNull] ExprParser.FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc([NotNull] ExprParser.FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReference([NotNull] ExprParser.ReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReference([NotNull] ExprParser.ReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.plainint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlainint([NotNull] ExprParser.PlainintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.plainint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlainint([NotNull] ExprParser.PlainintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.plainstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlainstring([NotNull] ExprParser.PlainstringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.plainstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlainstring([NotNull] ExprParser.PlainstringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.arglist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArglist([NotNull] ExprParser.ArglistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.arglist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArglist([NotNull] ExprParser.ArglistContext context);
}
