apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql
spec:
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: mysql-pvc  # persistentvolumeclaim.metadata.name
  containers:
  - name: mysql-container
    image: mysql
    volumeMounts:
      - name: myvol  # spec.volumes.name
        mountPath: /var/lib/mysql
    resources:
      limits:
        memory: "1024Mi"
        cpu: "2048m"
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: "NodePort"
  selector:
    name: mysql
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32006
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  password: secretpass

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  hostPath:
  # local:
    path: /run/desktop/mnt/host/wsl/mysql-data  # ~~pad in wsl: /mnt/wsl/mysql-data (moet eerst aangemaakt worden)~~
    ## correctie:
    ##  /run/desktop/mnt/host/wsl/mysql-data (docker-desktop)
    ##  verwijst naar /mnt/host/wsl/mysql-data (wsl)
    ##  en dus niet naar /mnt/wsl/mysql-data (wsl)
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname  # verwijst naar een van de labels voor de node (kubectl describe node docker-desktop)
          operator: In
          values:
          - docker-desktop  # de node waaronder kubernetes draait. In dit geval met docker desktop op windows

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  # storageClassName: hostpath # dit is de default
  storageClassName: hostpath
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
