services:
  rabbitmq:
    container_name: some-rabbit
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
  receiver:
    container_name: receiver
    image: x0backslash0x/labo206_helloworld:v1.0
    command: python -u receive.py
    depends_on:
      rabbitmq:
        condition: service_healthy
  sender:
    container_name: sender
    image: x0backslash0x/labo206_helloworld:v1.0
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: sleep infinity
    
  