services:
  rabbitmq:
    hostname: "rabbit-{{.Task.Slot}}"
    image: rabbitmq:management
    volumes:
      - "/mnt/mycephfs/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"
      # de erlang cookie moet op alle nodes van de cluster dezelfde zijn
      - "/mnt/mycephfs/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie:ro"
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      replicas: 3
  receiver:
    image: x0backslash0x/labo206_helloworld:v1.0
    command: python -u receive.py
    deploy:
      replicas: 1
  sender:
    image: x0backslash0x/labo206_helloworld:v1.0
    deploy:
      replicas: 15
    # script wordt nu om de x aantal seconden uitgevoerd
    command: /bin/sh -c "while true; do python send.py; sleep 5; done"
    
