apiVersion: apps/v1
kind: Deployment
metadata:
  name: authd
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: authc
        image: x0backslash0x/auth
        envFrom:
          - configMapRef:
              name: authm
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authm
data:
  MYSQL_HOST: localhost
  MYSQL_USER: authuser_user
  MYSQL_PASSWORD: Auth123
  MYSQL_DB: auth
  MYSQL_PORT: "5000"

